#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <chairosoft_quadrado_desktop_event_DesktopButtonDevice.h> // generated by nar-maven-plugin

JNIEXPORT jlong JNICALL Java_chairosoft_quadrado_desktop_event_DesktopButtonDevice_getId(JNIEnv * env, jobject obj) {
    return 12345;
}

JNIEXPORT void JNICALL Java_chairosoft_quadrado_desktop_event_DesktopButtonDevice_close(JNIEnv * env, jobject obj) {
    // nothing here right now
}
