// shim for Cygwin gcc
#ifdef __GNUC__
typedef long long __int64;
#endif

#include <stdio.h>
#include <stdlib.h>
//#include <bluetooth/bluetooth.h>
#include <jni.h>
#include <chairosoft_io_bluetooth_BluetoothDeviceProvider.h> // generated by nar-maven-plugin

JNIEXPORT void JNICALL
Java_chairosoft_io_bluetooth_BluetoothDeviceProvider_testBluetooth(JNIEnv * env, jclass clazz) {
    // nothing here right now
}
