#ifndef CHAIROSOFT_COMMON_H
#define CHAIROSOFT_COMMON_H

#include <jni.h>
#include <chairosoft_io_bluetooth_BluetoothDeviceProvider.h> // generated by nar-maven-plugin

int throw_new_RuntimeException(JNIEnv * env, const char* message);

#endif
