package chairosoft.quadrado.desktop.input.hid.jnaerated;
import com.ochafik.lang.jnaerator.runtime.CharByReference;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : hidapi/hidapi.h:48</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class hid_device_info extends Structure {
	/** C type : char* */
	public Pointer path;
	public short vendor_id;
	public short product_id;
	/** C type : wchar_t* */
	public CharByReference serial_number;
	public short release_number;
	/** C type : wchar_t* */
	public CharByReference manufacturer_string;
	/** C type : wchar_t* */
	public CharByReference product_string;
	public short usage_page;
	public short usage;
	public int interface_number;
	/** C type : hid_device_info* */
	public hid_device_info.ByReference next;
	public hid_device_info() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("path", "vendor_id", "product_id", "serial_number", "release_number", "manufacturer_string", "product_string", "usage_page", "usage", "interface_number", "next");
	}
	public hid_device_info(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends hid_device_info implements Structure.ByReference {
		
	};
	public static class ByValue extends hid_device_info implements Structure.ByValue {
		
	};
}
